code: python-data-structures
title: Python Data Structures
description: It covers the introductory material for lists, tuples, sets and dicts. Various problems involving these data structures would be covered in the functions related sections.
