code: getting-started-with-pandas
title: Getting started with Pandas
description: |
  This section introduces pandas library for data analysis. Understand the data structure and get the data ready for wrangling.
