code: numpy-array-basics
title: Numpy Array Basics
description: |
  Learn Numpy, a Python library that support large, multi-dimensional arrays and matrices. Understand single and multi-dimensional arrays, their data types and ways to create them.
