code: indexing-data-with-pandas
title: Indexing data with Pandas
description: |
  This section follows Getting started with pandas and includes indexing, slicing and selecting data based on condition.
